# project/docker-compose.yml

version: "3"
services:

  database:
    image: postgres:latest
    restart: always
    volumes:
        - ./backup_data/db:/var/lib/postgresql/data
    environment:
        - POSTGRES_DB=aaronfreightinc_db
        - POSTGRES_USER=aaronfreightinc
        - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
       - db_password

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # - ./backend_assets/static:/backend_assets/static
      # - ./backend_assets/media:/backend_assets/media
    environment:
      - SECRET_KEY_FILE=/run/secrets/backend_secret_key
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    depends_on:
      - database
    secrets:
       - db_password
       - backend_secret_key
  
#  frontend:
#    build: ./frontend
#    volumes:
#      - ./frontend:/app
#      - ./backend/static:/static
#      - ./backend/media:/media
#    depends_on:
#      - backend
#    ports:
#      - 80:80

  server:
    image: nginx
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./backend/static:/backend_assets/static
      - ./backend/media:/backend_assets/media
    depends_on:
      - backend


secrets:
   db_password:
     file: ./secrets/db_password.txt
   backend_secret_key:
     file: ./secrets/backend_secret_key.txt