# Generated by Django 4.2.1 on 2023-05-15 06:59

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Source Bakery', max_length=256)),
                ('address', models.CharField(blank=True, default=' 8601 Jefferson Street #101', max_length=128)),
                ('city', models.CharField(blank=True, default='Tolleson', max_length=128)),
                ('state', models.CharField(blank=True, default='AZ', max_length=2)),
                ('zip', models.CharField(blank=True, default='85353', max_length=5)),
                ('zip_extension', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'verbose_name_plural': 'addresses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Aaron Trucking, Inc.', max_length=256)),
                ('brand', models.ImageField(upload_to='media/brands/')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('phone_extension', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='housing_companies', to='invoices.address')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_companies', to='invoices.address')),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='Aaron', max_length=256)),
                ('last_name', models.CharField(default='Zepeda', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='7847X', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='771', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(help_text='Automatically filled in')),
                ('delivery_number', models.PositiveIntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='invoices.driver')),
                ('ship_from_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipped_from_invoices', to='invoices.address')),
                ('ship_to_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipped_to_invoices', to='invoices.address')),
                ('trailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='invoices.trailer')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='invoices.truck')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.PositiveIntegerField()),
                ('terms', models.IntegerField(choices=[(7, 'Net 7'), (15, 'Net 15'), (30, 'Net 30'), (60, 'Net 60'), (90, 'Net 90'), (120, 'Net 120')], default=30)),
                ('date', models.DateField(help_text='Automatically filled in')),
                ('due_date', models.DateField(help_text='Automatically filled in')),
                ('sales_number', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(upload_to='media/bill_of_ladings/')),
                ('invoiced_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoiced_invoices', to='invoices.company')),
                ('invoicing_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoicing_invoices', to='invoices.company')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoices.trip')),
            ],
        ),
    ]
