# Generated by Django 4.2.1 on 2023-05-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
