# Generated by Django 4.2.1 on 2023-05-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_invoice_number_alter_trip_trip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='brand',
            field=models.ImageField(upload_to='brands/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='attachment',
            field=models.FileField(upload_to='bill_of_ladings/'),
        ),
    ]
