# Generated by Django 4.2.1 on 2023-05-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_company_brand_alter_invoice_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='attachment',
        ),
        migrations.AddField(
            model_name='trip',
            name='attachment',
            field=models.FileField(default=123, upload_to='trips/attachments/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='brand',
            field=models.ImageField(upload_to='companies/brands'),
        ),
    ]
