# Generated by Django 4.2.1 on 2023-08-23 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_attachment_trip_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['date']},
        ),
    ]
