# Generated by Django 4.2.1 on 2023-08-23 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['date']},
        ),
    ]
