# Generated by Django 4.2.1 on 2023-08-23 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['invoice_number']},
        ),
    ]
